TaskGroupWeb/Controllers/LoginController.cs
using Acesso;
using AutoMapper;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using TaskGroupWeb.Helpers;
using TaskGroupWeb.Models;

namespace TaskGroupWeb.Controllers
{
    public class LoginController : Controller
    {
        public DbContext _db { get; set; }
        public IDataProtector _protector { get; set; }
        public IConfiguration _configuration { get; set; }

        private IMapper _mapper;
        private string _tipoAutenticacao;

        public LoginController(DbContext _db, IDataProtectionProvider protectionProvider, IConfiguration configuration, IMapper mapper)
        {
            this._db = _db;
            this._protector = protectionProvider.CreateProtector(configuration.GetSection("ChaveCriptografia").Value);
            this._configuration = configuration;
            this._mapper = mapper;

            _tipoAutenticacao = configuration.GetSection("TipoAuthenticacao").Value;
        }

        public IActionResult Index(string message = "")
        {
            TempData["Message"] = message;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserLogin(LoginModel _login)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _login.password = Crypter.GetMD5(_login.password);

                    var LoginStatus = false;
                    var _user = _db.DbUser.ValidateUser(_login.login, _login.password, out LoginStatus);

                    if (LoginStatus)
                    {
                        var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Name, _user.name),
                            new Claim("userId", _user.userId.ToString()),
                            new Claim("email", _user.login),
                            new Claim("contact", _user.contact),
                            new Claim("date.created", _user.dateCreated.ToString()),
                            new Claim("acesso", _user.acesso.ToString())
                        };

                        ClaimsIdentity userIdentity = new ClaimsIdentity(claims, _tipoAutenticacao);
                        ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);

                        await HttpContext.SignInAsync(principal);

                        //TempData["Message"] = "Success!";
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        TempData["Message"] = "Usuário ou senha incorretos!";
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    TempData["Message"] = "Por favor preencha todos os campos!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                Logger.SaveLog(e, _configuration);
                TempData["Message"] = "Ocorreu um erro inesperado!";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Logout(string message = "")
        {
            TempData.Clear();
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", new { message = message });
        }
    }
}

TaskGroupWeb/Controllers/UsersController.cs
using Acesso;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Objetos;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using TaskGroupWeb.Filters;
using TaskGroupWeb.Helpers;
using TaskGroupWeb.Models;
using static Objetos.DbEnumerators;

namespace TaskGroupWeb.Controllers
{
    [ClaimRequirementFilter("Administrador")]
    public class UsersController : Controller
    {
        public DbContext _db { get; set; }
        public IDataProtector _protector { get; set; }
        public IConfiguration _configuration { get; set; }

        private IMapper _mapper;
        private string _tipoAutenticacao;

        public UsersController(DbContext _db, IDataProtectionProvider protectionProvider, IConfiguration configuration, IMapper mapper)
        {
            this._db = _db;
            this._configuration = configuration;
            this._protector = protectionProvider.CreateProtector(configuration.GetSection("ChaveCriptografia").Value);            
            this._mapper = mapper;

            _tipoAutenticacao = configuration.GetSection("TipoAuthenticacao").Value;
        }

        #region GET
        public IActionResult Index(string message = "", OperationResult status = OperationResult.Success)
        {
            try
            {
                var users = _mapper.Map<IList<User>, IList<UserModel>>(_db.DbUser.List());

                TempData[status.ToString()] = message;
                return View(users);
            }
            catch (Exception e)
            {
                Logger.SaveLog(e, _configuration);
                TempData[OperationResult.Error.ToString()] = "Ocorreu um erro ao carregar usuários!";
                return RedirectToAction("Index", "Home");
            }            
        }

        public IActionResult Edit(string userId)
        {
            try
            {
                #region - Decrypt -

                var idUser = userId.DecryptUrl();

                #endregion

                var user = _db.DbUser.Select(idUser);
                var userModel = _mapper.Map<UserModel>(user);

                ArrangeDropDownToEdit(userModel);
                return View(userModel);
            }
            catch (Exception e)
            {
                Logger.SaveLog(e, _configuration);
                return RedirectToAction("Index", new { message = "Erro ao carregar usuário!", status = OperationResult.Error });
            }
        }

        public IActionResult Create()
        {
            ArrangeDropDownToCreate();
            return View();
        }

        #endregion

        #region POST

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(UserModel userModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userDb = _db.DbUser.Select(userModel.userId);
                    if (userDb.password != userModel.password)
                    {
                        userModel.password = Crypter.GetMD5(userModel.password);
                    }

                    var user = _mapper.Map<User>(userModel);
                    _db.DbUser.Update(user);

                    return Json(new
                    {
                        action = Url.Action("Index", new { message = "Usuário atualizado com sucesso!", status = OperationResult.Success }),
                        status = OperationResult.Success
                    });
                }
                else
                {
                    return Json(new
                    {
                        action = Url.Action("Index", new { message = "Por favor preencha todos os campos obrigatórios!", status = OperationResult.Error }),
                        status = OperationResult.Error
                    });
                }
            }
            catch (Exception e)
            {
                Logger.SaveLog(e, _configuration);

                return Json(new
                {
                    action = Url.Action("Index", new { message = "Erro ao atualizar usuário!", status = OperationResult.Error }),
                    status = OperationResult.Error
                });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(UserModel userModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    #region valida e-mail cadastrado

                    var isValid = false;
                    _db.DbUser.FindFromLogin(userModel.login, out isValid);

                    if (!isValid)
                    {
                        TempData[OperationResult.Error.ToString()] = "Já existe um usuário cadastrado com este e-mail!";
                        return View(userModel);
                    }

                    #endregion

                    userModel.password = Crypter.GetMD5(userModel.password);

                    var user = _mapper.Map<User>(userModel);                    
                    _db.DbUser.Insert(user);

                    return RedirectToAction("Index", new { message = "Usuário salvo com sucesso!", status = OperationResult.Success });
                }
                else
                {
                    TempData[OperationResult.Error.ToString()] = "Por favor preencha todos os campos obrigatórios!";
                    return View(userModel);
                }
            }
            catch (Exception e)
            {
                Logger.SaveLog(e, _configuration);
                TempData[OperationResult.Error.ToString()] = "Erro ao salvar usuário";
                return View(userModel);
            }
        }

        #endregion

        #region - UTILS -

        private void ArrangeDropDownToCreate()
        {
            ViewBag.Status = HtmlHelpers.GetDropDownFromEnum<UserStatus>((int)UserStatus.Ativo);
            ViewBag.NivelAcesso = HtmlHelpers.GetDropDownFromEnum<UserAcesso>((int)UserAcesso.Usuario);
        }

        private void ArrangeDropDownToEdit(UserModel user)
        {
            ViewBag.Status = HtmlHelpers.GetDropDownFromEnum<UserStatus>((int)user.status);
            ViewBag.NivelAcesso = HtmlHelpers.GetDropDownFromEnum<UserAcesso>((int)user.acesso);
        }

        #endregion
    }
}

TaskGroupWeb/Views/Shared/_BreadCrumb.cshtml
@if (TempData["breadcrumb"] != null)
{
    <div>
        @Html.Raw(TempData["breadcrumb"].ToString())
    </div>
}

TaskGroupWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskGroupWeb</title>

    <link rel="stylesheet" href="~/lib/sb-admin/vendor/fontawesome-free/css/all.min.css" />

    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/sb-admin/css/sb-admin-2.css" />
    <link rel="stylesheet" href="~/css/font-awesome-animation.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/SweetAlert/swalExtend.css" />
    <link rel="stylesheet" href="~/css/SweetAlert/sweetalert.css" />

    @RenderSection("css", required: false)
</head>

<body id="page-top">

    <div class="modal-loading"></div>

    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home")">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Task Group <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a asp-area="" class="nav-link" asp-controller="Home" asp-action="Index">
                    <i class="fas fa-fw fa-home"></i>
                    <span>Home</span>
                </a>
            </li>
            <!-- Heading -->
            <div class="sidebar-heading">
                Tarefas
            </div>

            @*<li class="nav-item">
            <a asp-area="" class="nav-link" asp-controller="Tasks" asp-action="Index">
                <i class="fas fa-fw fa-tasks"></i>
                <span>Tarefas</span>
            </a>
        </li>*@

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Tarefas</span>
                </a>

                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages" data-parent="#accordionSidebar">

                    <div class="bg-white py-2 collapse-inner rounded" id="list-projects">

                        <!-- Lista de projetos -->

                    </div>
                </div>

            </li>

            <!-- Heading -->
            <div class="sidebar-heading">
                Configurações
            </div>

            @if (User.HasClaim("acesso", "Administrador"))
            {
                <!-- Nav Item - Tables -->
                <li class="nav-item">
                    <a asp-area="" class="nav-link" asp-controller="Users" asp-action="Index">
                        <i class="fas fa-fw fa-user"></i>
                        <span>Usuários</span>
                    </a>
                </li>
            }

            <li class="nav-item">
                <a asp-area="" class="nav-link" asp-controller="Projects" asp-action="Index">
                    <i class="fas fa-fw fa-project-diagram"></i>
                    <span>Projetos</span>
                </a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-nav-top topbar mb-4 static-top shadow">
                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small" placeholder="Pesquisar..." aria-label="Search" aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>
                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@User.Identity.Name</span>
                                <img class="img-profile rounded-circle" src="~/images/user.png">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Informaçoes
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Sair
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>

                @*<partial name="_CookieConsentPartial" />*@ 
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">

                    @RenderBody()

                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; TaskGroup @DateTime.Now.Year</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a asp-area="" asp-controller="Login" asp-action="Logout" class="btn btn-primary">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/sb-admin/vendor/jquery/jquery.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <script src="~/lib/sb-admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sb-admin/vendor/jquery-easing/jquery.easing.min.js"></script>
    <script src="~/lib/sb-admin/js/sb-admin-2.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/lib/SweetAlert/swalExtend.js"></script>
    <script src="~/lib/SweetAlert/sweetalert.js"></script>

    <script>

        $(document).ready(function () {

            LoadingHide();

            submitAssync('@Url.Action("GetProjects", "Projects")', null,
                function (response) {

                    response.projects.forEach((project, index) => {

                        let url = '@Url.Action("Index", "Tasks")';
                        let html = `<a class="collapse-item project-item project_${project._projectId}" href="${url}?_projectId=${project._projectId}">${project.name} </a>`;
                        $('#list-projects').append(html);
                    })
                },
                function (response) {
                    let html = `<a class="collapse-item" href="#">Não foi possível carregar os projetos</a>`;
                    $('#list-projects').append(html);
                })

            $('[data-toggle="tooltip"]').tooltip();
        })

    </script>

    @RenderSection("scripts", required: false)

</body>
</html>

TaskGroupWeb/Views/Shared/_MessageResult.cshtml
@using TaskGroupWeb.Helpers

@if (TempData[OperationResult.Error.ToString()] != null && !string.IsNullOrEmpty(TempData[OperationResult.Error.ToString()].ToString()))
{
    <p class="alert alert-danger">@TempData[OperationResult.Error.ToString()]</p>
}
else if (TempData[OperationResult.Success.ToString()] != null && !string.IsNullOrEmpty(TempData[OperationResult.Success.ToString()].ToString()))
{
    <p class="alert alert-success">@TempData[OperationResult.Success.ToString()]</p>
}